#!/bin/bash

sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman-key --populate holo
sudo pacman-key --refresh-keys

. scripts/install_lein
. scripts/install_neovim
. scripts/install_xclip
. scripts/install_podman-compose
