#!/bin/bash

. scripts/initialize_pacman

. scripts/install_lein
. scripts/install_neovim
. scripts/install_xclip
. scripts/install_podman-compose

. scipts/install_virtualenv
. scipts/install_tesseract_jpn
