#!/bin/bash

install_neovim() {
    version=${1:-nightly}
    echo "Installing nvim ${version}..."
    nvim="${HOME}/bin/nvim"
    nvimurl="https://github.com/neovim/neovim/releases/download/${version}/nvim-linux-x86_64.appimage"
    mkdir -p "$(dirname "$nvim")"
    curl -fL "$nvimurl" -o "$nvim" -z "$nvim"
    chmod u+x "$nvim"
}

install_neovim
