#!/bin/bash

# See: https://github.com/mathewthe2/Game2Text

function make_game2text {
    # The requirements may need to be slightly adjusted if e.g. the specific version of numpy is not available
    # TODO: Replace == with >= in requirements.py automatically
    # TODO: In config.ini replace `browser = default` with `browser = chromium` automatically
    # See: https://game2text.com/faq/switch-browser/
    pip install -r requirements.txt
}

sudo steamos-readonly disable && \
sudo pacman base-devel glibc linux-api-headers zlib cmake python3 gcc nodejs npm libffi openssl rust tk tcl && \
sudo steamos-readonly enable && \
git clone https://github.com/mathewthe2/Game2Text.git && \
cd Game2Text && \
virtualenv venv --python='/usr/bin/python' && \
source venv/bin/activate && \
pip install virtualenv && \
make_game2text && \
deactivate

# TODO: Create a script for this and put it on the path
echo 'Run "source venv/bin/activate && python game2text.py ; deactivate" to start game2text'
