#!/bin/bash

function install_podman_compose {
    echo "Installing aardvark-dns and podman-compose..."
    sudo pacman -S aardvark-dns podman-compose
}

sudo steamos-readonly disable
install_podman_compose
sudo steamos-readonly enable
